name: SAST
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fluidattacks/sast-action@1.3.0
        id: scan
        with:
          scan_config_path: .github/sast-config.yaml

      # - name: Fail if vulnerabilities found
      #  if: steps.scan.outputs.vulnerabilities_found == 'true'
      #  run: exit 1

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: results-sast.csv
